nota1 = input('Digite a nota1: ')
nota2 = input('Digite a nota2: ')
nota3 = input('Digite a nota3: ')
nota4 = input('Digite a nota4: ')
print('A media  das notas é: ', (int(nota1) + int(nota2) + int(nota3) + int(nota4)) / 4)