num1 = input('Digite o primeiro número: ')
num2 = input('Digite o segundo número: ')
num3 = input('Digite o terceiro número: ')
print('O dobro do num1 + a metade de num2 + num3 é igual a: ', (int(num1) * 2 + int(num2) /2 + int(num3)))
print('A soma do triplo do num1 + num3 * num2 é igaul a: ', (int(num1) * 3 + int(num3) * int(num2)))